experiment:
  name: rt_proxy_rts
  seed: 42
  save_dir: checkpoints/
  save: False # Save trained models and/ or results
  
paths:
  data_dir: data/                  # Local or absolute path to data folder
  save_dir: checkpoints/          # Where to save model checkpoints, logs
  results_dir: results/           # Optional: for evaluation outputs, plots
  # rts_scenario_data_dir: 'C:\Users\ucbva19\OneDrive - University College London\RTS_GMLC_data' 
  # pglib_data_dir: 'C:\Users\ucbva19\Git projects\pglib-opf' 
  rts_scenario_data_dir: 'C:\Users\akyla\OneDrive - University College London\RTS_GMLC_data' 
  pglib_data_dir: 'C:\Users\akyla\pglib-opf' 


shared_data:
  reserves: 0 # Reserve requirements, percentage of aggregate error [0.05, 0.025, 0, nan]
  frequency: '1h'
  horizon: 1
  ramping: True # Including ramping constraints (for multi-period formulation only)
  lag_measurements: 3
  validation_perc: 0.15
splits:    
  train_start: '2020-01-01'
  test_start:  '2020-09-01'

models:

  norm:
    class: NormEBM
    hidden_sizes: [128, 128, 128]
    mse_reg_weight: 1
    sq_reg_weight: 0.0
    lr: 0.001
    batch_size: 512
    epochs: 500
    weight_decay: 0.0001
    warm_start: True
    max_grad_norm: 2
    orthog_reg_weight: 1